version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - npm install
      - sam build
  post_build:
    commands:
      - sam package --s3-bucket codepipeline-us-east-1-929407174816  --output-template-file packaged.yaml
      - sam deploy --template-file packaged.yaml --stack-name skydemostack --capabilities CAPABILITY_IAM
